version: '3'

services:

    php:
        build: docker/php
        volumes:
            - "./:/project:cached"
        depends_on:
            - mysql

    nginx:
        build: docker/nginx
        volumes:
            - "./:/project:cached"
        depends_on:
            - php

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD="
            - "MYSQL_DATABASE=yourdatabase"

    node:
        build: docker/node
        volumes:
            - "./:/project"
        depends_on:
            - nginx
